// <auto-generated />
using EmpleosDoApi.DATA;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EmpleosDoApi.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20221124003634_inicio")]
    partial class inicio
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.10");

            modelBuilder.Entity("EmpleosDoApi.Model.Empleos", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("area")
                        .HasColumnType("TEXT");

                    b.Property<string>("fechaPublicacion")
                        .HasColumnType("TEXT");

                    b.Property<string>("informacionVacante")
                        .HasColumnType("TEXT");

                    b.Property<string>("logoEmpresa")
                        .HasColumnType("TEXT");

                    b.Property<string>("modalida")
                        .HasColumnType("TEXT");

                    b.Property<string>("nombreEmpresa")
                        .HasColumnType("TEXT");

                    b.Property<string>("nombreVacante")
                        .HasColumnType("TEXT");

                    b.Property<string>("paginaWeb")
                        .HasColumnType("TEXT");

                    b.Property<string>("requisitoVacante")
                        .HasColumnType("TEXT");

                    b.Property<double>("salario")
                        .HasColumnType("REAL");

                    b.Property<string>("tipo")
                        .HasColumnType("TEXT");

                    b.Property<string>("ubicacion")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Empleos");
                });
#pragma warning restore 612, 618
        }
    }
}
